version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: pricing-calculator-backend-test
    environment:
      - NODE_ENV=production
      - PORT=5001
      - HOST=0.0.0.0
      - DATABASE_PATH=./pricing.db
      - FRONTEND_URL=http://localhost:3000
      - ALLOWED_ORIGINS=http://localhost:3000
      - JWT_SECRET=pricing-calculator-jwt-secret-2025-test
      - JWT_REFRESH_SECRET=pricing-calculator-refresh-secret-2025-test
      - LOG_LEVEL=info
    ports:
      - "5001:5001"
    volumes:
      - pricing_data_test:/app/data
      - pricing_logs_test:/app/logs
    networks:
      - pricing_network_test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=http://localhost:5001/api
        - PUBLIC_URL=/pricingapp
    container_name: pricing-calculator-frontend-test
    ports:
      - "3000:80"
    networks:
      - pricing_network_test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  pricing_data_test:
    driver: local
  pricing_logs_test:
    driver: local

networks:
  pricing_network_test:
    driver: bridge
