services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pricing-calculator-backend
    env_file:
      - ./server/.env.production
    volumes:
      - pricing_data:/app/data
      - pricing_logs:/app/logs
    networks:
      - pricing_network
    restart: unless-stopped
    ports:
      - "5001:5001"  # Esposto come in locale
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:5001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://luke.febos.local:5001
        - PUBLIC_URL=/pricingapp
    container_name: pricing-calculator-frontend
    env_file:
      - ./client/.env.production
    ports:
      - "3000:80"  # Esposto come in locale
    networks:
      - pricing_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

# Nginx rimosso - usiamo architettura semplice come in locale

volumes:
  pricing_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker/pricingapp_data/database
  pricing_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker/pricingapp_data/logs
  pricing_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker/pricingapp_data/static

networks:
  pricing_network:
    driver: bridge
