global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "pricing-calculator-backend"
    static_configs:
      - targets: ["backend:5001"]
    metrics_path: "/api/metrics"
    scrape_interval: 30s

  - job_name: "pricing-calculator-nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/nginx_status"
    scrape_interval: 30s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
