# ===========================================
# PRICING CALCULATOR v0.1 - Docker Compose
# ===========================================

services:
  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pricing-calculator-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5001
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:80,http://127.0.0.1:80,http://localhost,http://127.0.0.1
    volumes:
      - backend_data:/app/data
    ports:
      - "5001:5001"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:5001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5001/api
    container_name: pricing-calculator-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (opzionale per produzione)
  nginx:
    image: nginx:alpine
    container_name: pricing-calculator-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    profiles:
      - production

volumes:
  backend_data:
    driver: local

networks:
  default:
    name: pricing-calculator-network
